sys: unix
#for inkscape flatpak change 'apt' to 'flatpak'
inkscapeVer: flatpak

#Color profiles and file extensions
#for export .JPG you can use Image Magick
rgbExt: [PNG, SVG, EPS, PDF]
cmykExt: [JPG, EPS, PDF]

#Background colors
jpgBgColor: white
jpgBgPositive: white
jpgBgNegative: black